version: '3.8'

services:
  blockscout-frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'blockscout-ui'
    env_file:
      -  ../env/.env.blockscout.frontend
