version: "3.6"

services:
  besu-node1:
    extends:
      file: services/nodes/docker-compose-besu-node1.yml
      service: besu-node1

  besu-node2:
    extends:
      file: services/nodes/docker-compose-besu-node2.yml
      service: besu-node2

  besu-node3:
    extends:
      file: services/nodes/docker-compose-besu-node3.yml
      service: besu-node3

  besu-node4:
    extends:
      file: services/nodes/docker-compose-besu-node4.yml
      service: besu-node4

  api:
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=http://localhost:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
    depends_on:
      - mongodb
    networks:
      - epirus

  mongodb:
    image: mongo:5.0.8
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"
    networks:
      - epirus

  web:
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
      - DISPLAY_NETWORK_TAB=disabled
    depends_on:
      - api
    networks:
      - epirus

  ingestion:
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=http://localhost:8545
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      - epirus

  nginx:
    image: nginx:latest
    volumes:
      - ./services/nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - ${PORT:-80}:80
    depends_on:
      - api
      - web
    networks:
      - epirus

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

  epirus:
    name: epirus-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
