services:
  besu:
    image: hyperledger/besu:latest
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    environment:
      - BESU_RPC_HTTP_ENABLED=true
      - BESU_RPC_WS_ENABLED=true
      - BESU_NETWORK=goerli
      - BESU_GENESIS_FILE=/config/genesis.json
    volumes:
      - ./config:/config
