services:
  besu-node1:
    extends:
      file: ./services/nodes/docker-compose-besu-node1.yml
      service: besu-node1

  besu-node2:
    extends:
      file: ./services/nodes/docker-compose-besu-node2.yml
      service: besu-node2

  besu-node3:
    extends:
      file: ./services/nodes/docker-compose-besu-node3.yml
      service: besu-node3

  besu-node4:
    extends:
      file: ./services/nodes/docker-compose-besu-node4.yml
      service: besu-node4

#  client-node:
#    extends:
#      file: ./services/nodes/docker-compose-client-node1.yml
#      service: client-node

  blockscout:
    extends:
      file: ./services/docker-compose-blockscout.yml
      service: blockscout

  blockscout-db:
    extends:
      file: ./services/docker-compose-blockscout-db.yml
      service: blockscout-db

  blockscout-redis-db:
    extends:
      file: ./services/docker-compose-blockscout-redis.yml
      service: blockscout-redis-db

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

