services:
  besu:
    image: hyperledger/besu:latest
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    environment:
      - BESU_RPC_HTTP_ENABLED=true
      - BESU_RPC_WS_ENABLED=true
      - BESU_RPC_HTTP_API=ETH,NET,WEB3,ADMIN,DEBUG,PERM,QBFT
      - BESU_RPC_WS_API=ETH,NET,WEB3,ADMIN,DEBUG,PERM,QBFT
      - BESU_RPC_HTTP_CORS_ORIGINS=all
      - BESU_NETWORK=goerli
      - BESU_HOST_ALLOWLIST=*
      - BESU_GENESIS_FILE=/config/genesis.json
      - BESU_DATA_PATH=/config/node-1/data
    volumes:
      - ./qbft-network:/config
