version: '3.8'

services:
  blockscout:
    depends_on:
      - blockscout-db
      - smart-contract-verifier
      - blockscout-redis-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest} # option to lock into a specific version
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.2.2
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - blockscout-db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - env/.env.blockscout
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/
