version: '3.8'

services:
  blockscout-redis-db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: blockscout-redis-db
    command: redis-server
    volumes:
      - ./blockscout-redis-data:/data
